{% set python_min = '3.10' %}
{% set name = "ibis-ml" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ibis_ml-{{ version }}.tar.gz
  sha256: 88472dae8b1228b5bc1c39dabf1b984124c026ad186ec1cc85a5528bb59b5ead

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - ibis-framework

test:
  imports:
    - ibis_ml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ibis-project.github.io/ibis-ml/
  summary: IbisML is a library for building scalable ML pipelines using Ibis.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deepyaman
    - gforsyth
